version: '3'

services:
  soj:
    image: jkswing/soj
    restart: unless-stopped
    environment:
      REDIS_HOST: soj-redis
      REDIS_PORT: 6379
#      REDIS_PASSWORD:
      PAGE_SIZE: 20
      DB_HOST: db
      DB_PASSWORD: soj
      DJANGO_SETTINGS_MODULE: soj.pro
    volumes:
      - problems:/usr/src/soj/shared_data/problems
      - staticfiles:/usr/src/soj/shared_data/static_files
    networks:
      - soj-net
    deploy:
      mode: replicated
      replicas: 2

  #MySQL Service
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: soj
      MYSQL_USER: soj
      MYSQL_PASSWORD: soj
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql/
#       - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - soj-net

  soj-redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - soj-net

  soj-judger:
    image: jkswing/soj-judger
    depends_on:
      - soj-redis
    restart: unless-stopped
    environment:
      REDIS_HOST: soj-redis
      REDIS_PORT: 6379
#      REDIS_PASSWORD:
      SOJ_HOST: soj:8000
    networks:
      - soj-net
    volumes:
      - problems:/usr/src/judger/problems
      - submissions:/usr/src/judger/submissions
    deploy:
      mode: replicated
      replicas: 6

  soj-frontend:
    image: jkswing/soj-frontend
    depends_on:
      - soj
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - soj-net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/usr/share/nginx/html/static

networks:
  soj-net:
    driver: overlay

volumes:  # TODO driver?
  dbdata: {}
  problems:
    driver: vieux/sshfs
    driver_opts:
      sshcmd: "soj@47.106.234.124:/path/to/problems"
      password: "xxxyyy"
  staticfiles: {}
  submissions:
    driver: vieux/sshfs
    driver_opts:
      sshcmd: "soj@47.106.234.124:/path/to/submissions"
      password: "xxxyyy"
